# Generated by Django 3.2.3 on 2021-05-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210507_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['id'], 'verbose_name': '项目表', 'verbose_name_plural': '项目表'},
        ),
    ]
