# Generated by Django 3.2.3 on 2021-05-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interfaces',
            options={'ordering': ['id'], 'verbose_name': '接口表', 'verbose_name_plural': '接口表'},
        ),
    ]
