# Generated by Django 3.2 on 2021-05-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210430_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='ids',
        ),
        migrations.AddField(
            model_name='projects',
            name='id',
            field=models.AutoField(default=1, help_text='项目主键', primary_key=True, serialize=False, verbose_name='项目主键'),
            preserve_default=False,
        ),
    ]
